/* AUTOGENERATED BY Project-Lewis — DO NOT EDIT */
#ifndef LEWIS_QUANTIZATION_PARAMS_H
#define LEWIS_QUANTIZATION_PARAMS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Quantization parameters for input/output tensors (INT8 -> float dequantization).
 *
 * float_value = (int8_value - zero_point) * scale
 */
typedef struct {
    float scale;
    int32_t zero_point;
} lewis_quantization_params_t;

#define LEWIS_QUANTIZATION_PARAMS_INPUT_SCALE 0.0297280233f
#define LEWIS_QUANTIZATION_PARAMS_INPUT_ZERO_POINT -4
#define LEWIS_QUANTIZATION_PARAMS_OUTPUT_SCALE 0.0039062500f
#define LEWIS_QUANTIZATION_PARAMS_OUTPUT_ZERO_POINT -128

static const lewis_quantization_params_t lewis_quantization_params = {
    .scale = 0.0297280233f,
    .zero_point = -4,
};

static const lewis_quantization_params_t lewis_quantization_params_output = {
    .scale = 0.0039062500f,
    .zero_point = -128,
};

#ifdef __cplusplus
}
#endif

#endif /* LEWIS_QUANTIZATION_PARAMS_H */
