#!/usr/bin/env python3
"""Gera fixtures do modelo A2-full para o firmware test harness (T5, C09).

Para N janelas do split ``chapman-record-disjoint-val0.1-seed13`` (selecionadas
com seed 42), emite em ``firmware/tests/fixtures/generated/pretrain_a2_full_fixtures.h``:

- entradas int8 (regra "away from zero" do firmware, scale/zp de entrada);
- logits int8 esperados (interpretador TFLite Python com resolver BUILTIN_REF,
  a referencia de bit-exatidao do QG8 — CMSIS-NN pode divergir 1 LSB);
- probabilidades calibradas esperadas (logits -> /T -> sigmoid, float32).

Uso:
    uv run python firmware/scripts/generate_pretrain_fixtures.py [--n 16]
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

import numpy as np
import tensorflow as tf

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.quantize_pretrain_a2_full import (  # noqa: E402
    apply_int8_dequant_temperature_sigmoid,
    quantize_away_from_zero,
)
from src.models.pretrain_chapman import build_datasets  # noqa: E402

LOGGER = logging.getLogger("lewis.camada09.pretrain_fixtures")

QUANT_DIR = PROJECT_ROOT / "experiments" / "20260728_053011_pretrain_chapman" / "quantized"
RUN_DIR = QUANT_DIR.parent
OUT_PATH = (
    PROJECT_ROOT / "firmware" / "tests" / "fixtures" / "generated" / "pretrain_a2_full_fixtures.h"
)


def _collect_val_windows() -> tuple[np.ndarray, np.ndarray]:
    provenance = json.loads((RUN_DIR / "provenance.json").read_text(encoding="utf-8"))
    training = provenance["training"]
    _, val_ds, _, val_steps = build_datasets(
        val_ratio=0.1,
        batch_size=training["batch_size"],
        segment_len=provenance["model"]["input_shape"][1],
        seed=provenance["seed"],
        steps_per_epoch=1,
        validation_steps=training["validation_steps"],
    )
    xs, ys = [], []
    for xb, yb in val_ds.take(val_steps):
        xs.append(xb.numpy())
        ys.append(yb.numpy())
    return np.concatenate(xs), np.concatenate(ys)


def _predict_logits_builtin_ref(tflite_bytes: bytes, X_q: np.ndarray) -> np.ndarray:
    interpreter = tf.lite.Interpreter(
        model_content=tflite_bytes,
        experimental_op_resolver_type=tf.lite.experimental.OpResolverType.BUILTIN_REF,
    )
    interpreter.allocate_tensors()
    in_idx = interpreter.get_input_details()[0]["index"]
    out_idx = interpreter.get_output_details()[0]["index"]
    logits = []
    for sample in X_q:
        interpreter.set_tensor(in_idx, sample[np.newaxis, ...])
        interpreter.invoke()
        logits.append(interpreter.get_tensor(out_idx)[0].copy())
    return np.stack(logits).astype(np.int8)


def _fmt_int8(arr: np.ndarray, per_line: int = 16) -> str:
    vals = [str(int(v)) for v in np.asarray(arr).ravel()]
    lines = [", ".join(vals[i : i + per_line]) for i in range(0, len(vals), per_line)]
    return ",\n    ".join(lines)


def _fmt_float(arr: np.ndarray) -> str:
    return ", ".join(f"{float(v):.8e}f" for v in arr)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n", type=int, default=16)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    params = json.loads((QUANT_DIR / "quantization_params.json").read_text(encoding="utf-8"))
    tflite_bytes = (QUANT_DIR / "a2_full_int8.tflite").read_bytes()
    in_scale = float(params["input"]["scale"])
    in_zp = int(params["input"]["zero_point"])
    out_scale = float(params["output"]["scale"])
    out_zp = int(params["output"]["zero_point"])
    temperature = float(params["temperature"])

    LOGGER.info("reconstruindo split val (seed 13)...")
    X, y = _collect_val_windows()
    rng = np.random.default_rng(args.seed)
    indices = np.sort(rng.choice(len(X), size=args.n, replace=False))
    LOGGER.info("fixtures: %d janelas, indices=%s", args.n, indices.tolist())

    X_q = quantize_away_from_zero(X[indices], in_scale, in_zp)
    logits = _predict_logits_builtin_ref(tflite_bytes, X_q)
    probs = apply_int8_dequant_temperature_sigmoid(logits, out_scale, out_zp, temperature)
    pseudo = y[indices].argmax(axis=1)

    lines = [
        "/* AUTOGENERATED BY Project-Lewis — DO NOT EDIT",
        " *",
        " * Fixtures do modelo A2-full (T5, C09).",
        f" * Split: {params['split_version']} | indices (seed {args.seed}): {indices.tolist()}",
        f" * sha256_tflite: {params['sha256_tflite']}",
        " * Referencia: TFLite Python BUILTIN_REF; CMSIS-NN pode divergir 1 LSB.",
        " */",
        "#ifndef PRETRAIN_A2_FULL_FIXTURES_H",
        "#define PRETRAIN_A2_FULL_FIXTURES_H",
        "#include <stdint.h>",
        "",
        f"#define PRETRAIN_A2_FULL_FIXTURE_COUNT {args.n}",
        "",
    ]
    for i in range(args.n):
        lines.append(
            f"/* fixture {i}: val_idx={int(indices[i])} pseudo_class={int(pseudo[i])} */"
        )
        lines.append(f"static const int8_t pretrain_a2_fx{i}_input[500] = {{")
        lines.append(f"    {_fmt_int8(X_q[i])}")
        lines.append("};")
        lines.append(f"static const int8_t pretrain_a2_fx{i}_logits[5] = {{")
        lines.append(f"    {_fmt_int8(logits[i])}")
        lines.append("};")
        lines.append(f"static const float pretrain_a2_fx{i}_probs[5] = {{")
        lines.append(f"    {_fmt_float(probs[i])}")
        lines.append("};")
        lines.append("")
    ptr_inputs = ",\n    ".join(f"pretrain_a2_fx{i}_input" for i in range(args.n))
    ptr_logits = ",\n    ".join(f"pretrain_a2_fx{i}_logits" for i in range(args.n))
    ptr_probs = ",\n    ".join(f"pretrain_a2_fx{i}_probs" for i in range(args.n))
    lines.append(f"static const int8_t* const pretrain_a2_fx_inputs[{args.n}] = {{")
    lines.append(f"    {ptr_inputs}")
    lines.append("};")
    lines.append(f"static const int8_t* const pretrain_a2_fx_logits[{args.n}] = {{")
    lines.append(f"    {ptr_logits}")
    lines.append("};")
    lines.append(f"static const float* const pretrain_a2_fx_probs[{args.n}] = {{")
    lines.append(f"    {ptr_probs}")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* PRETRAIN_A2_FULL_FIXTURES_H */")
    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    LOGGER.info("fixtures salvas em %s (%d bytes)", OUT_PATH, OUT_PATH.stat().st_size)
    return 0


if __name__ == "__main__":
    sys.exit(main())
