"""Exportação TensorFlow Lite + header C + parâmetros de quantização.

Gera:
- model_int8.tflite   : FlatBuffer quantizado INT8 full-integer.
- model_int8.h        : Array C portátil (sem xxd), com include guards,
                        alignas(16) e metadados (SHA256, versão, data).
- quantization_params.json : scales e zero_points de entrada/saída.
"""

from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Optional

import numpy as np
import tensorflow as tf

from src.quantization.ptq import calibrate

LOGGER = logging.getLogger("lewis.camada05.export_tflite")


def extract_quantization_params(
    tflite_model: bytes,
    output_path: Path | str,
) -> dict:
    """Extrai scales e zero_points do modelo quantizado.

    Parameters
    ----------
    tflite_model : bytes
        Conteúdo do modelo TFLite quantizado.
    output_path : Path | str
        Caminho para salvar o JSON.

    Returns
    -------
    dict
        Dicionário com parâmetros de entrada e saída.
    """
    output_path = Path(output_path)
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    params = {
        "input": {
            "scale": float(input_details["quantization_parameters"]["scales"][0]),
            "zero_point": int(input_details["quantization_parameters"]["zero_points"][0]),
            "dtype": str(np.dtype(input_details["dtype"])),
        },
        "output": {
            "scale": float(output_details["quantization_parameters"]["scales"][0]),
            "zero_point": int(output_details["quantization_parameters"]["zero_points"][0]),
            "dtype": str(np.dtype(output_details["dtype"])),
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        json.dump(params, fh, indent=2, ensure_ascii=False)

    LOGGER.info("Parâmetros de quantização salvos: %s", output_path)
    return params


def generate_quantization_header(
    params: dict,
    header_path: Path | str,
    struct_name: str = "lewis_quantization_params",
) -> str:
    """Gera header C com parâmetros de quantização input/output.

    Parameters
    ----------
    params : dict
        Dicionário retornado por ``extract_quantization_params``.
    header_path : Path | str
        Caminho para salvar o header.
    struct_name : str
        Nome da struct e dos defines no header.

    Returns
    -------
    str
        Conteúdo do header gerado.
    """
    header_path = Path(header_path)
    header_path.parent.mkdir(parents=True, exist_ok=True)

    guard = f"{struct_name.upper()}_H"
    content = f"""/* AUTOGENERATED BY Project-Lewis — DO NOT EDIT */
#ifndef {guard}
#define {guard}

#ifdef __cplusplus
extern "C" {{
#endif

#include <stdint.h>

/* Quantization parameters for input/output tensors (INT8 -> float dequantization).
 *
 * float_value = (int8_value - zero_point) * scale
 */
typedef struct {{
    float scale;
    int32_t zero_point;
}} {struct_name}_t;

#define {struct_name.upper()}_INPUT_SCALE {params['input']['scale']:.10f}f
#define {struct_name.upper()}_INPUT_ZERO_POINT {params['input']['zero_point']}
#define {struct_name.upper()}_OUTPUT_SCALE {params['output']['scale']:.10f}f
#define {struct_name.upper()}_OUTPUT_ZERO_POINT {params['output']['zero_point']}

static const {struct_name}_t {struct_name} = {{
    .scale = {params['input']['scale']:.10f}f,
    .zero_point = {params['input']['zero_point']},
}};

static const {struct_name}_t {struct_name}_output = {{
    .scale = {params['output']['scale']:.10f}f,
    .zero_point = {params['output']['zero_point']},
}};

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
"""
    header_path.write_text(content, encoding="utf-8")
    LOGGER.info("Header de quantização gerado: %s", header_path)
    return content


def generate_c_header(
    tflite_model: bytes,
    header_path: Path | str,
    array_name: str = "lewis_model_int8",
    version: str = "1.0.0",
) -> str:
    """Gera header C puro a partir do FlatBuffer TFLite.

    Não depende de xxd. Produz array ``alignas(16)`` para alinhamento
    exigido por alguns interpretadores TFLM, include guards e metadados.

    Parameters
    ----------
    tflite_model : bytes
        Conteúdo do modelo TFLite.
    header_path : Path | str
        Caminho para salvar o header.
    array_name : str
        Nome base das variáveis no header.
    version : str
        Versão do artefato.

    Returns
    -------
    str
        Conteúdo do header gerado.
    """
    header_path = Path(header_path)
    header_path.parent.mkdir(parents=True, exist_ok=True)

    sha256 = hashlib.sha256(tflite_model).hexdigest()
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    length = len(tflite_model)

    var_data = f"{array_name}_tflite"
    var_len = f"{array_name}_len"

    hex_lines = []
    bytes_per_line = 12
    for i in range(0, length, bytes_per_line):
        chunk = tflite_model[i : i + bytes_per_line]
        hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
        hex_lines.append(f"    {hex_values},")

    array_body = "\n".join(hex_lines)

    header_content = f"""/* AUTOGENERATED BY Project-Lewis — DO NOT EDIT */
#ifndef {array_name.upper()}_TFLITE_H
#define {array_name.upper()}_TFLITE_H

#ifdef __cplusplus
extern "C" {{
#endif

#include <stddef.h>
#include <stdint.h>

/* Model metadata */
#define {array_name.upper()}_VERSION "{version}"
#define {array_name.upper()}_SHA256 "{sha256}"
#define {array_name.upper()}_GENERATED_AT "{timestamp}"

__attribute__((section(".rodata.model"), aligned(16)))
static const unsigned char {var_data}[] = {{
{array_body}
}};

static const unsigned int {var_len} = {length};

#ifdef __cplusplus
}}
#endif

#endif /* {array_name.upper()}_TFLITE_H */
"""

    header_path.write_text(header_content, encoding="utf-8")
    LOGGER.info("Header C gerado: %s (%d bytes)", header_path, length)
    return header_content


def export_tflite(
    model: tf.keras.Model,
    representative_data: Callable,
    output_dir: Path | str,
    model_name: str = "model_int8",
    version: str = "1.0.0",
    allow_float: bool = False,
) -> Path:
    """Exporta modelo Keras para conjunto TFLM INT8.

    Parameters
    ----------
    model : tf.keras.Model
        Modelo treinado em float32.
    representative_data : Callable
        Generator de dados representativos.
    output_dir : Path | str
        Diretório de saída.
    model_name : str
        Nome base dos arquivos.
    version : str
        Versão do artefato.
    allow_float : bool
        Permite fallback float se necessário.

    Returns
    -------
    Path
        Caminho do .tflite gerado.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    tflite_path = output_dir / f"{model_name}.tflite"
    header_path = output_dir / f"{model_name}.h"
    params_path = output_dir / "quantization_params.json"
    quant_header_path = output_dir / "quantization_params.h"

    tflite_model = calibrate(
        model,
        representative_data,
        allow_float=allow_float,
    )

    tflite_path.write_bytes(tflite_model)
    LOGGER.info("TFLite salvo: %s (%.2f KB)", tflite_path, len(tflite_model) / 1024)

    params = extract_quantization_params(tflite_model, params_path)
    generate_c_header(
        tflite_model,
        header_path,
        array_name=model_name.replace("-", "_").replace(".", "_"),
        version=version,
    )
    generate_quantization_header(
        params,
        quant_header_path,
        struct_name="lewis_quantization_params",
    )

    return tflite_path


def validate_tflm_size(tflite_path: Path | str, max_kb: int = 64) -> bool:
    """Valida se FlatBuffer está dentro do limite TFLM.

    Parameters
    ----------
    tflite_path : Path | str
        Caminho do .tflite.
    max_kb : int
        Tamanho máximo em KB.

    Returns
    -------
    bool
        True se dentro do limite.
    """
    tflite_path = Path(tflite_path)
    size_kb = tflite_path.stat().st_size / 1024
    passes = size_kb <= max_kb
    LOGGER.info(
        "TFLM size: %.2f KB (limite: %d KB) — %s",
        size_kb,
        max_kb,
        "OK" if passes else "EXCEDE",
    )
    return passes


def main(
    model_path: Optional[Path] = None,
    output_dir: Optional[Path] = None,
    model_name: str = "model_int8",
) -> Path:
    """Entry-point CLI para exportação TFLite.

    Parameters
    ----------
    model_path : Path | None
        Caminho do modelo Keras. Se None, usa modelo dummy.
    output_dir : Path | None
        Diretório de saída.
    model_name : str
        Nome base dos arquivos.

    Returns
    -------
    Path
        Caminho do .tflite gerado.
    """
    logging.basicConfig(level=logging.INFO)

    if output_dir is None:
        output_dir = Path("models/quantized")

    if model_path is not None:
        model = tf.keras.models.load_model(model_path)
    else:
        from src.models.backbone_1d import build_backbone_1d
        from src.quantization.ptq import representative_dataset_random

        model = build_backbone_1d(input_len=500, num_classes=5)
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
        X = np.random.randn(100, 500, 1).astype(np.float32)
        rep_data = representative_dataset_random(X, n_samples=50, seed=42)
        return export_tflite(model, rep_data, output_dir, model_name=model_name)

    # Modelo carregado de arquivo — usa dados aleatórios como placeholder.
    from src.quantization.ptq import representative_dataset_random

    input_shape = model.input_shape
    length = input_shape[1] if input_shape[1] is not None else 500
    channels = input_shape[2] if input_shape[2] is not None else 1
    X = np.random.randn(100, length, channels).astype(np.float32)
    rep_data = representative_dataset_random(X, n_samples=50, seed=42)

    return export_tflite(model, rep_data, output_dir, model_name=model_name)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Export TFLM INT8 para Project-Lewis")
    parser.add_argument(
        "--model-path",
        type=Path,
        default=None,
        help="Caminho do modelo Keras (.keras ou .h5).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("models/quantized"),
        help="Diretório de saída.",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        default="model_int8",
        help="Nome base dos arquivos gerados.",
    )
    args = parser.parse_args()
    main(args.model_path, args.output_dir, args.model_name)
