from __future__ import annotations

from typing import Any


def nvmlInit() -> None: ...
def nvmlShutdown() -> None: ...
def nvmlDeviceGetCount() -> int: ...
def nvmlDeviceGetHandleByIndex(index: int) -> Any: ...
def nvmlDeviceGetMemoryInfo(handle: Any) -> Any: ...
def nvmlDeviceGetUtilizationRates(handle: Any) -> Any: ...
def nvmlDeviceGetTemperature(handle: Any, sensor: int) -> int: ...
