"""Exporta os headers C do modelo A2-full INT8 para o firmware (T4, C08).

Gera TRÊS headers novos em ``firmware/src/ml/`` — sem tocar nos headers
existentes (stage1/stage2/quantization_params.h, intocados por AC-4.3):

- ``pretrain_a2_full_int8.h``         FlatBuffer INT8 (via generate_c_header)
- ``pretrain_a2_full_quant_params.h`` scales/zero-points (macros prefixadas
                                      PRETRAIN_A2_FULL_QUANT_PARAMS_*)
- ``pretrain_a2_full_config.h``       T=0.3741, dims, versão, SHA-256

Integridade fail-closed: o SHA-256 do .tflite deve bater com
``quantization_params.json`` (gerado na T3).

Uso:
    uv run python scripts/export_pretrain_a2_full_headers.py
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.quantization.export_tflite import (  # noqa: E402
    generate_c_header,
    generate_quantization_header,
)

LOGGER = logging.getLogger("lewis.camada05.export_a2_full")

DEFAULT_QUANT_DIR = (
    PROJECT_ROOT / "experiments" / "20260728_053011_pretrain_chapman" / "quantized"
)
DEFAULT_FW_DIR = PROJECT_ROOT / "firmware" / "src" / "ml"
TEMPERATURE = 0.3741036858061345  # fallback; main() lê de quantization_params.json
VERSION = "3.1.0"


def build_config_header(
    *,
    temperature: float,
    sha256_tflite: str,
    run_id: str,
    version: str,
) -> str:
    """Conteúdo do pretrain_a2_full_config.h (T como const float, dims, metadados)."""
    return f"""/* AUTOGENERATED BY Project-Lewis — DO NOT EDIT
 *
 * Config do modelo pré-treinado A2-full (a1_stable+focal, Chapman).
 * Inferência: logits int8 -> dequant (scale/zp) -> /T -> sigmoid.
 * T < 1 (underconfidence, Mukhoti 2020); /T aplicado em float32,
 * sem caminho de overflow int8.
 */
#ifndef PRETRAIN_A2_FULL_CONFIG_H
#define PRETRAIN_A2_FULL_CONFIG_H

#ifdef __cplusplus
extern "C" {{
#endif

#define PRETRAIN_A2_FULL_VERSION "{version}"
#define PRETRAIN_A2_FULL_SOURCE_RUN "{run_id}"
#define PRETRAIN_A2_FULL_TFLITE_SHA256 "{sha256_tflite}"

#define PRETRAIN_A2_FULL_INPUT_LEN 500
#define PRETRAIN_A2_FULL_OUTPUT_LEN 5

/* Temperature scaling (T1, calibration.json). Ordem: logits -> /T -> sigmoid. */
static const float PRETRAIN_A2_FULL_TEMPERATURE = {temperature:.10f}f;

#ifdef __cplusplus
}}
#endif

#endif /* PRETRAIN_A2_FULL_CONFIG_H */
"""


def export_headers(tflite_bytes: bytes, params: dict, out_dir: Path) -> list[Path]:
    """Escreve os 3 headers em ``out_dir``. Levanta ValueError se o sha256 divergir."""
    sha = hashlib.sha256(tflite_bytes).hexdigest()
    expected = params.get("sha256_tflite")
    if expected and sha != expected:
        raise ValueError(f"sha256 do .tflite diverge de quantization_params.json: {sha} != {expected}")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    model_h = out_dir / "pretrain_a2_full_int8.h"
    quant_h = out_dir / "pretrain_a2_full_quant_params.h"
    config_h = out_dir / "pretrain_a2_full_config.h"

    generate_c_header(
        tflite_bytes,
        model_h,
        array_name="pretrain_a2_full_int8",
        version=VERSION,
    )
    generate_quantization_header(
        {"input": params["input"], "output": params["output"]},
        quant_h,
        struct_name="pretrain_a2_full_quant_params",
    )
    config_h.write_text(
        build_config_header(
            temperature=float(params["temperature"]),
            sha256_tflite=sha,
            run_id=params.get("source_run", "20260728_053011_pretrain_chapman"),
            version=VERSION,
        ),
        encoding="utf-8",
    )
    LOGGER.info("headers gerados em %s", out_dir)
    return [model_h, quant_h, config_h]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quant-dir", type=Path, default=DEFAULT_QUANT_DIR)
    parser.add_argument("--fw-dir", type=Path, default=DEFAULT_FW_DIR)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    tflite_path = args.quant_dir / "a2_full_int8.tflite"
    params = json.loads(
        (args.quant_dir / "quantization_params.json").read_text(encoding="utf-8")
    )
    params["source_run"] = args.quant_dir.parent.name
    try:
        written = export_headers(tflite_path.read_bytes(), params, args.fw_dir)
    except ValueError as exc:
        LOGGER.error("%s (fail-closed)", exc)
        return 3
    for path in written:
        LOGGER.info("%s (%d bytes)", path.name, path.stat().st_size)
    return 0


if __name__ == "__main__":
    sys.exit(main())
