#!/usr/bin/env python3
"""Gera coeficientes IIR para filtros DSP do firmware Project-Lewis.

Os filtros sao projetados deterministicamente com SciPy e exportados como:
  * firmware/src/dsp/filter_coeffs.h  (arrays const float para C)
  * tests/fixtures/dsp_filters.py     (referencia Python para testes)

Filtros:
  * Bandpass Butterworth 0.5-40 Hz, ordem 4, fs=500 Hz (causal SOS).
  * Notch 60 Hz, largura ~2 Hz (Q=30), fs=500 Hz (causal SOS).

A implementacao em C usa transposed direct-form II biquad cascade.
Os coeficientes sao armazenados como [b0, b1, b2, a1, a2] por secao.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import numpy as np
from scipy import signal

PROJECT_ROOT = Path(__file__).resolve().parents[1]
C_HEADER_PATH = PROJECT_ROOT / "firmware" / "src" / "dsp" / "filter_coeffs.h"
PYTHON_FIXTURE_PATH = PROJECT_ROOT / "tests" / "fixtures" / "dsp_filters.py"

FS = 500.0
LOWCUT = 0.5
HIGHCUT = 40.0
BANDPASS_ORDER = 4
NOTCH_FREQ = 60.0
NOTCH_BW = 2.0


def design_bandpass_sos(fs: float, lowcut: float, highcut: float, order: int) -> np.ndarray:
    """Projeta bandpass Butterworth causal em SOS."""
    sos = signal.iirfilter(
        N=order,
        Wn=[lowcut, highcut],
        fs=fs,
        btype="band",
        ftype="butter",
        output="sos",
    )
    return sos


def design_notch_sos(fs: float, f0: float, bw: float) -> np.ndarray:
    """Projeta notch em SOS a partir de f0 e largura de banda (Hz)."""
    q = f0 / bw if bw > 0.0 else 1e6
    b, a = signal.iirnotch(w0=f0, Q=q, fs=fs)
    sos = signal.tf2sos(b, a)
    return sos


def sos_to_flat_coeffs(sos: np.ndarray) -> tuple[list[float], int]:
    """Converte SOS [b0,b1,b2,a0,a1,a2] -> flat [b0,b1,b2,a1,a2] por secao."""
    n_sections = sos.shape[0]
    flat: list[float] = []
    for row in sos:
        b0, b1, b2, a0, a1, a2 = row
        if not math.isclose(a0, 1.0, rel_tol=1e-9, abs_tol=1e-12):
            # Normaliza para a0 = 1.0 garantindo estabilidade numerica.
            b0, b1, b2 = b0 / a0, b1 / a0, b2 / a0
            a1, a2 = a1 / a0, a2 / a0
        flat.extend([float(b0), float(b1), float(b2), float(a1), float(a2)])
    return flat, n_sections


def format_c_array(flat: list[float], name: str, sections: int) -> str:
    """Formata array float para header C."""
    lines = [
        f"#define {name}_SECTIONS {sections}",
        f"static const float {name}_coeffs[{sections} * 5] = {{",
    ]
    for i in range(sections):
        base = i * 5
        coeffs = flat[base : base + 5]
        cstr = ", ".join(f"{c:.9e}f" for c in coeffs)
        lines.append(f"    /* section {i} */ {cstr},")
    lines.append("};")
    return "\n".join(lines)


def format_python_array(flat: list[float], sections: int, var_name: str) -> str:
    """Formata array numpy 2-D (sections x 5) para fixture Python."""
    lines = [f"{var_name}_FLAT = np.array(["]
    for i in range(sections):
        base = i * 5
        coeffs = flat[base : base + 5]
        cstr = ", ".join(f"{c:.9e}" for c in coeffs)
        lines.append(f"    # section {i}")
        lines.append(f"    {cstr},")
    lines.append("], dtype=np.float32)")
    lines.append(f"{var_name} = {var_name}_FLAT.reshape(-1, 5)")
    return "\n".join(lines)


def generate_c_header(
    bp_flat: list[float], bp_sections: int, notch_flat: list[float], notch_sections: int
) -> str:
    header = """/* AUTOGENERATED BY scripts/generate_filter_coeffs.py — DO NOT EDIT */
#ifndef LEWIS_FILTER_COEFFS_H
#define LEWIS_FILTER_COEFFS_H

#ifdef __cplusplus
extern "C" {{
#endif

/* Coeficientes IIR projetados em Python com SciPy (causal SOS).
 * Formato por secao: [b0, b1, b2, a1, a2]
 * Implementacao: transposed direct-form II biquad cascade.
 */

{bandpass}

{notch}

#ifdef __cplusplus
}}
#endif

#endif /* LEWIS_FILTER_COEFFS_H */
"""
    return header.format(
        bandpass=format_c_array(bp_flat, "LEWIS_BANDPASS", bp_sections),
        notch=format_c_array(notch_flat, "LEWIS_NOTCH", notch_sections),
    )


def generate_python_fixture(
    bp_flat: list[float],
    bp_sections: int,
    notch_flat: list[float],
    notch_sections: int,
) -> str:
    fixture = '''"""Referencia Python para os filtros DSP do firmware.

Gerado automaticamente por scripts/generate_filter_coeffs.py.
Contem os mesmos coeficientes SOS causais usados em C e uma implementacao
biquad transposed direct-form II equivalente.
"""

from __future__ import annotations

import numpy as np
from scipy import signal

FS = 500.0
LOWCUT = 0.5
HIGHCUT = 40.0
BANDPASS_ORDER = 4
NOTCH_FREQ = 60.0
NOTCH_BW = 2.0

{bp_array}

{notch_array}


def _biquad_sample(x: float, coeffs: np.ndarray, state: np.ndarray) -> float:
    """Processa uma amostra em uma secao biquad (transposed DF-II)."""
    b0, b1, b2, a1, a2 = coeffs
    d0, d1 = state[0], state[1]
    y = b0 * x + d0
    state[0] = b1 * x - a1 * y + d1
    state[1] = b2 * x - a2 * y
    return y


def _cascade_sample(x: float, coeffs: np.ndarray, states: np.ndarray) -> float:
    """Processa uma amostra em cascata de biquads."""
    n_sections = coeffs.shape[0]
    y = x
    for i in range(n_sections):
        y = _biquad_sample(y, coeffs[i], states[i])
    return y


def cascade_process_block(
    input_arr: np.ndarray,
    coeffs: np.ndarray,
    states: np.ndarray | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Processa um bloco em cascata de biquads.

    Returns
    -------
    output, states
    """
    n = len(input_arr)
    out = np.empty(n, dtype=np.float32)
    n_sections = coeffs.shape[0]
    if states is None:
        states = np.zeros((n_sections, 2), dtype=np.float32)
    for i in range(n):
        out[i] = _cascade_sample(float(input_arr[i]), coeffs, states)
    return out, states


def bandpass_filter(
    x: np.ndarray,
    states: np.ndarray | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Filtro passa-banda 0.5-40 Hz (causal)."""
    return cascade_process_block(x, BANDPASS_COEFFS, states)


def notch_filter(
    x: np.ndarray,
    states: np.ndarray | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Filtro notch 60 Hz (causal)."""
    return cascade_process_block(x, NOTCH_COEFFS, states)


def filter_chain(
    x: np.ndarray,
    bp_states: np.ndarray | None = None,
    notch_states: np.ndarray | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Pipeline bandpass -> notch (causal)."""
    y, bp_states = bandpass_filter(x, bp_states)
    y, notch_states = notch_filter(y, notch_states)
    return y, bp_states, notch_states


def design_coefficients() -> tuple[np.ndarray, np.ndarray]:
    """Reproduz o projeto dos coeficientes (para auditoria)."""
    bp_sos = signal.iirfilter(
        N=BANDPASS_ORDER,
        Wn=[LOWCUT, HIGHCUT],
        fs=FS,
        btype="band",
        ftype="butter",
        output="sos",
    )
    q = NOTCH_FREQ / NOTCH_BW
    b, a = signal.iirnotch(w0=NOTCH_FREQ, Q=q, fs=FS)
    notch_sos = signal.tf2sos(b, a)
    return bp_sos.astype(np.float32), notch_sos.astype(np.float32)
'''
    return fixture.format(
        bp_array=format_python_array(bp_flat, bp_sections, "BANDPASS_COEFFS"),
        notch_array=format_python_array(notch_flat, notch_sections, "NOTCH_COEFFS"),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Gera coeficientes IIR para firmware DSP.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verifica se os arquivos gerados estao sincronizados (nao escreve).",
    )
    args = parser.parse_args()

    bp_sos = design_bandpass_sos(FS, LOWCUT, HIGHCUT, BANDPASS_ORDER)
    notch_sos = design_notch_sos(FS, NOTCH_FREQ, NOTCH_BW)

    bp_flat, bp_sections = sos_to_flat_coeffs(bp_sos)
    notch_flat, notch_sections = sos_to_flat_coeffs(notch_sos)

    c_header = generate_c_header(bp_flat, bp_sections, notch_flat, notch_sections)
    py_fixture = generate_python_fixture(bp_flat, bp_sections, notch_flat, notch_sections)

    # Normaliza formatacao do fixture Python para comparacao deterministica.
    try:
        import black

        py_fixture = black.format_str(py_fixture, mode=black.Mode(line_length=100))
    except ImportError:
        pass

    if args.check:
        c_existing = C_HEADER_PATH.read_text(encoding="utf-8") if C_HEADER_PATH.exists() else ""
        py_existing = (
            PYTHON_FIXTURE_PATH.read_text(encoding="utf-8") if PYTHON_FIXTURE_PATH.exists() else ""
        )
        if c_existing != c_header or py_existing != py_fixture:
            print("ERROR: filter coefficients are out of sync with generator", file=sys.stderr)
            return 1
        print("OK: filter coefficients are synchronized")
        return 0

    C_HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    PYTHON_FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    C_HEADER_PATH.write_text(c_header, encoding="utf-8")
    PYTHON_FIXTURE_PATH.write_text(py_fixture, encoding="utf-8")

    print(f"[generate] {C_HEADER_PATH}")
    print(f"[generate] {PYTHON_FIXTURE_PATH}")
    print(f"[info] bandpass sections={bp_sections}, notch sections={notch_sections}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
