/* AUTOGENERATED BY Project-Lewis — DO NOT EDIT
 *
 * Aggregate header for two-stage v2.0 quantized models.
 * Includes the individual FlatBuffer headers produced by
 * scripts/quantize_two_stage_v2.0.py.
 */
#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ml/stage1_int8_v2.0.h"
#include "ml/stage2_int8_v2.0.h"

#ifdef __cplusplus
}
#endif

#endif /* MODEL_DATA_H */
