/* AUTOGENERATED BY Project-Lewis — DO NOT EDIT */
#ifndef PRETRAIN_A2_FULL_QUANT_PARAMS_H
#define PRETRAIN_A2_FULL_QUANT_PARAMS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Quantization parameters for input/output tensors (INT8 -> float dequantization).
 *
 * float_value = (int8_value - zero_point) * scale
 */
typedef struct {
    float scale;
    int32_t zero_point;
} pretrain_a2_full_quant_params_t;

#define PRETRAIN_A2_FULL_QUANT_PARAMS_INPUT_SCALE 0.0784313753f
#define PRETRAIN_A2_FULL_QUANT_PARAMS_INPUT_ZERO_POINT -1
#define PRETRAIN_A2_FULL_QUANT_PARAMS_OUTPUT_SCALE 0.0338943601f
#define PRETRAIN_A2_FULL_QUANT_PARAMS_OUTPUT_ZERO_POINT -15

static const pretrain_a2_full_quant_params_t pretrain_a2_full_quant_params = {
    .scale = 0.0784313753f,
    .zero_point = -1,
};

static const pretrain_a2_full_quant_params_t pretrain_a2_full_quant_params_output = {
    .scale = 0.0338943601f,
    .zero_point = -15,
};

#ifdef __cplusplus
}
#endif

#endif /* PRETRAIN_A2_FULL_QUANT_PARAMS_H */
