/* AUTOGENERATED BY Project-Lewis — DO NOT EDIT
 *
 * Config do modelo pré-treinado A2-full (a1_stable+focal, Chapman).
 * Inferência: logits int8 -> dequant (scale/zp) -> /T -> sigmoid.
 * T < 1 (underconfidence, Mukhoti 2020); /T aplicado em float32,
 * sem caminho de overflow int8.
 */
#ifndef PRETRAIN_A2_FULL_CONFIG_H
#define PRETRAIN_A2_FULL_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define PRETRAIN_A2_FULL_VERSION "3.1.0"
#define PRETRAIN_A2_FULL_SOURCE_RUN "20260728_053011_pretrain_chapman"
#define PRETRAIN_A2_FULL_TFLITE_SHA256 "7d27dc402ba9b2c7b73f90f7016a68b2bfc09e2d0b27f2a20bbb3e76b8a362be"

#define PRETRAIN_A2_FULL_INPUT_LEN 500
#define PRETRAIN_A2_FULL_OUTPUT_LEN 5

/* Temperature scaling (T1, calibration.json). Ordem: logits -> /T -> sigmoid. */
static const float PRETRAIN_A2_FULL_TEMPERATURE = 0.3741036858f;

#ifdef __cplusplus
}
#endif

#endif /* PRETRAIN_A2_FULL_CONFIG_H */
