/* AUTOGENERATED BY scripts/generate_filter_coeffs.py — DO NOT EDIT */
#ifndef LEWIS_FILTER_COEFFS_H
#define LEWIS_FILTER_COEFFS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Coeficientes IIR projetados em Python com SciPy (causal SOS).
 * Formato por secao: [b0, b1, b2, a1, a2]
 * Implementacao: transposed direct-form II biquad cascade.
 */

#define LEWIS_BANDPASS_SECTIONS 4
static const float LEWIS_BANDPASS_coeffs[4 * 5] = {
    /* section 0 */ 2.138798733e-03f, 4.277597465e-03f, 2.138798733e-03f, -1.227875879e+00f, 3.935230602e-01f,
    /* section 1 */ 1.000000000e+00f, 2.000000000e+00f, 1.000000000e+00f, -1.486663673e+00f, 6.949675580e-01f,
    /* section 2 */ 1.000000000e+00f, -2.000000000e+00f, 1.000000000e+00f, -1.988215471e+00f, 9.882564157e-01f,
    /* section 3 */ 1.000000000e+00f, -2.000000000e+00f, 1.000000000e+00f, -1.995246749e+00f, 9.952864068e-01f,
};

#define LEWIS_NOTCH_SECTIONS 1
static const float LEWIS_NOTCH_coeffs[1 * 5] = {
    /* section 0 */ 9.875889381e-01f, -1.439842705e+00f, 9.875889381e-01f, -1.439842705e+00f, 9.751778762e-01f,
};

#ifdef __cplusplus
}
#endif

#endif /* LEWIS_FILTER_COEFFS_H */
